### ISSUE TITLE
Gulp Error 

### ISSUE THREAD

**Issue by cmarchena** [JeremyEnglert/JointsWP#252]
Hi, after a fresh install: 
`[21:03:44] Using gulpfile ~/Local Sites/nameofthesite/app/public/wp-content/themes/JointsWP/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
`

**Comment by AmyGail** [comment]
I have the same error.

**Comment by arjendejong12** [comment]
You need to `npm install gulp-cli -g`.

**Comment by JeremyEnglert** [comment]
Thanks @arjendejong12!
