### ISSUE TITLE
Compiling scripts no longer works

### ISSUE THREAD

**Issue by jossafossa** [JeremyEnglert/JointsWP#331]
I've just freshly installed jointsWP and got this message when compiling scripts with `gulp watch` or `gulp scripts`.

```
[00:26:05] Using gulpfile D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\gulpfile.js
[00:26:05] Starting 'watch'...
[00:26:10] Starting 'scripts'...
[00:26:11] 'scripts' errored after 921 ms
[00:26:11] Error: File not found with singular glob: D:/xampp/htdocs/fairplay/wp-content/themes/Fairplay/node_modules/what-input/dist/what-input.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\readable.js:84:17)
    at Glob.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:197:8)
    at done (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:688:12)
    at D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:676:10
    at Glob._stat2 (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:772:12)
    at lstatcb_ (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:764:12)
[00:26:11] 'watch' errored after 5.43 s
```

When running `npm install` i also got an error:
```
npm WARN optional dep failed, continuing fsevents@1.1.3

> jointswp-sass@5.0.0 postinstall D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay
> npm run build


> jointswp-sass@5.0.0 build D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay
> gulp

[00:32:46] Using gulpfile D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\gulpfile.js
[00:32:46] Starting 'default'...
[00:32:46] Starting 'styles'...
[00:32:46] Starting 'scripts'...
[00:32:46] Starting 'images'...
[00:32:48] 'scripts' errored after 1.84 s
[00:32:48] Error: File not found with singular glob: D:/xampp/htdocs/fairplay/wp-content/themes/Fairplay/node_modules/what-input/dist/what-input.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\readable.js:84:17)
    at Glob.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:197:8)
    at done (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:688:12)
    at D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:676:10
    at Glob._stat2 (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:772:12)
    at lstatcb_ (D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\glob\glob.js:764:12)
[00:32:48] 'default' errored after 1.84 s
[00:32:48] The following tasks did not complete: styles, images
[00:32:48] Did you forget to signal async completion?

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "C:\\Users\\JossaFossa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.2.4
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! jointswp-sass@5.0.0 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jointswp-sass@5.0.0 build script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jointswp-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls jointswp-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\npm-debug.log

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! jointswp-sass@5.0.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jointswp-sass@5.0.0 postinstall script 'npm run build'.
npm ERR! This is most likely a problem with the jointswp-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls jointswp-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\htdocs\fairplay\wp-content\themes\Fairplay\npm-debug.log
```

**Comment by JeremyEnglert** [comment]
Try running `npm install` again. It looks like what-input didn't install.

**Comment by JeremyEnglert** [comment]
Does this file ` D:/xampp/htdocs/fairplay/wp-content/themes/Fairplay/node_modules/what-input/dist/what-input.js` exist?

**Comment by garrett-eclipse** [comment]
As Jeremy indicated it may be file missing which prompts the possibility of an incomplete node_modules directory, your best bet is to clear it with `rm -rf node_models`
Then go with your `npm install` and `npm run build`

You mentioned gulp commands though so it begs the question is you're on JointsWP 4 over the current 5 which runs all commands through npm run;
http://jointswp.com/docs/getting-started-sass/

I also found a related thread on gulp;
https://github.com/gulpjs/gulp/issues/1253#issuecomment-145633579

Which indicated you may want to run a `npm update` event before your initial `npm install`

If you're still running into this after the reset and it's what-input.js that's missing you can install it specifically with `npm install what-input`

**Comment by jossafossa** [comment]
@garrett-eclipse Thanks, I fixed it! Installing what-input seperately did the trick.

**Comment by garrett-eclipse** [comment]
Good stuff @jossafossa, all the best
