### ISSUE TITLE
Error compiling styles

### ISSUE THREAD

**Issue by heyfella** [JeremyEnglert/JointsWP#380]
I no longer seem to be able to compile the styles. I receive the following error

```
Error: It's not clear which file to import for '@import "../../../node_modules/foundation-sites/scss/foundation"'.
       Candidates:
         ../../../node_modules/foundation-sites/scss/foundation.scss
         ../../../node_modules/foundation-sites/scss/foundation.css
       Please delete or rename all but one of these files.
        on line 15 of assets/styles/scss/style.scss
>> @import "../../../node_modules/foundation-sites/scss/foundation";
```

I have tried removing ```rm -rf node_modules``` and then running install ```npm install``` but the install fails and I receive this error

```
Unhandled rejection Error: Command failed: /usr/bin/git checkout 4.01.0.0
error: pathspec '4.0' did not match any file(s) known to git.

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

**Comment by mlangone** [comment]
There is a new package.json and gulpfile.js in the repo that fixes this
error, replace your local with these and then rm rf the node modules and
run npm install again.

**Comment by JeremyEnglert** [comment]
@mlangone is correct! Grab the newest package.json and you should be good to go.
