### ISSUE TITLE
Getting error at gulp serve-Cannot find module '@microsoft/sp-build-web'

### ISSUE THREAD

**Issue by riksranjan** [JeremyEnglert/JointsWP#401]
Hi, 

i got this error when i enter gulp serve

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\rranjan\REACTGetItems\gulpfile.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)

**Comment by garretthyder** [comment]
Hi @riksranjan 

It appears you're attempting to implement the Sharepoint Framework here;
https://www.npmjs.com/package/@microsoft/sp-build-web

As your gulp is complaining about the package missing I assume you've not included it into the project yet.
You can do this one of two ways;
1. Add it to your package.json and run `npm install`
2. Manually install it for the current dev env;
`npm install --save-dev @microsoft/sp-build-web`

That should install the dependencies, then from there your gulpfile.js customizations fall outside of the JWP framework so am closing this.

Cheers

**Comment by JackWan** [comment]
Got exactly the same error. When trying npm install I noticed a message:

"npm WARN notsup Unsupported engine for karma@0.13.22: wanted: {"node":"0.10 || 0.12 || 4 || 5"} (current: {"node":"8.17.0","npm":"6.13.4"})

My node version seems to be too high. nvm list available/nvm install 4.9.1/npm install (no error now)/gulp serve (succeeded!)
