### ISSUE TITLE
JointsWP won't install on Mac or Windows

### ISSUE THREAD

**Issue by sirchuy** [JeremyEnglert/JointsWP#440]
I'm running into the same error on Windows and Mac when attempting to npm install JointsWP. I've tried changing the gulp-sass version as some suggested and downgraded Node but no success. Any help with this would be appreciated - I really like developing using Joints but I can't wait for too long before I need to find a new framework.

npm ERR! code 1
npm ERR! path /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/Cellar/node/17.6.0_1/bin/node /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/Cellar/node/17.6.0_1/bin/node',
npm ERR! gyp verb cli   '/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.6.0 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb 'which' failed Error: not found: python2
npm ERR! gyp verb 'which' failed     at getNotFoundError (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:13:12)
npm ERR! gyp verb 'which' failed     at F (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:68:19)
npm ERR! gyp verb 'which' failed     at E (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:80:29)
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:89:16
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/index.js:42:5
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb 'which' failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb 'which' failed  python2 Error: not found: python2
npm ERR! gyp verb 'which' failed     at getNotFoundError (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:13:12)
npm ERR! gyp verb 'which' failed     at F (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:68:19)
npm ERR! gyp verb 'which' failed     at E (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:80:29)
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:89:16
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/index.js:42:5
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb 'which' failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb 'which' failed   code: 'ENOENT'
npm ERR! gyp verb 'which' failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb 'which' failed Error: not found: python
npm ERR! gyp verb 'which' failed     at getNotFoundError (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:13:12)
npm ERR! gyp verb 'which' failed     at F (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:68:19)
npm ERR! gyp verb 'which' failed     at E (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:80:29)
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:89:16
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/index.js:42:5
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb 'which' failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb 'which' failed  python Error: not found: python
npm ERR! gyp verb 'which' failed     at getNotFoundError (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:13:12)
npm ERR! gyp verb 'which' failed     at F (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:68:19)
npm ERR! gyp verb 'which' failed     at E (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:80:29)
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:89:16
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/index.js:42:5
npm ERR! gyp verb 'which' failed     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb 'which' failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb 'which' failed   code: 'ENOENT'
npm ERR! gyp verb 'which' failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/17.6.0_1/bin/node" "/[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /[REDACTED PATH]/wordpress/wp-content/themes/[REDACTED THEME]/node_modules/node-sass
npm ERR! gyp ERR! node -v v17.6.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sirchuy/.npm/_logs/2023-03-28T13_54_43_337Z-debug-0.log

**Comment by garretthyder** [comment]
@sirchuy looks like you're missing python or it's misconfigured.

Your errors repeat the mention a few times;
> Error: not found: python2
> Error: Can't find Python executable "python", you can set the PYTHON env variable.

For Windows - https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#environment-setup-and-configuration
Try running `npm install -g windows-build-tools`

For Mac install python2 and setup the path. 
https://docs.python-guide.org/starting/install/osx/

Feel free to re-open if I missed the mark there.

**Comment by sirchuy** [comment]
No joy. I did discover a problem with my python path on my Mac and resolved it, but now I have a new set of errors. I've attached the file this time as it is pretty long.

Incidentally, Homebrew doesn't appear to have a keg for Python any longer. It presents an error when attempting to install it via the instruction you linked. But it did point me in the right direction to get my Python up and running again.

[npmerror-installingjointswp-202303281854.txt](https://github.com/JeremyEnglert/JointsWP/files/11095015/npmerror-installingjointswp-202303281854.txt)

**Comment by garretthyder** [comment]
O well, worth the shot. I'll reopen as it wasn't as simple as I'd hoped.

Wild shot, your node is reporting at `node -v v17.6.0`, I believe I read somewhere node-sass loses support in node V14+.

You can try a downgrade of node.js using the `n` tool;
`npm install -g n`
`n 13.14.`
Then confirm;
`node -v`
`npm install`
`npm run build`
